new Morris.Donut({
    element: 'sectoral',

    data:[
        {label: "Nuclear industry", value: 20},
        {label: "Precious metals and diamonds industry", value: 12},
        {label: "Electric-power industry", value: 82},
        {label: "Chemistry and oil chemistry industry", value: 29},
        {label: "Iron industry", value: 27},
        {label: "Non-ferrous industry", value: 16},
        {label: "Oil and gas industry", value: 45},
        {label: "Banks and other investment and finance organizations", value: 69},
        {label: "Housing and utility sector", value: 7},
        {label: "Forest, wood-pulp and paper industry", value: 8},
        {label: "Healthcare and pharmaceutical industry", value: 10},
        {label: "Coil industry", value: 11},
        {label: "Insurance", value: 12},
        {label: "Engineering", value: 34},
        {label: "Food industry", value: 38},
        {label: "Transport", value: 44},
        {label: "Construction materials industry", value: 7},
        {label: "Telecommunications", value: 17},
        {label: "Construction", value: 35},
        {label: "Service companies", value: 17},
        {label: "Wholesale trade", value: 164},
        {label: "Agricultural industry", value: 28},
        {label: "Retail", value: 79},
        {label: "Information technologies", value: 15},
        {label: "Mass media", value: 13},
        {label: "Other sectors", value: 118},
    ],
    colors:[
        "#FFFFCC",
        "#FFCC66",
        "#FF9900",
        "#FFCC99",
        "#FF6633",
        "#FFCCCC",
        "#CC9999",
        "#FF6699",
        "#FF99CC",
        "#FF66CC",
        "#FFCCFF",
        "#CC99CC",
        "#CC66FF",
        "#CC99FF",
        "#9966CC",
        "#CCCCFF",
        "#9999CC",
        "#3333FF",
        "#6699FF",
        "#0066FF",
        "#99CCFF",
        "#66CCFF",
        "#99CCCC",
        "#CCFFFF",
        "#99FFCC",
        "#66CC99",
        "#66FF99",
        "#99FF99",
        "#CCFFCC",
        "#33FF33",
        "#CCFF66",
        "#CCCC66",
        "#990066",
    ],
    resize:true

});